### ISSUE TITLE
Add support for Windows arm64

### ISSUE THREAD

**Issue by mhalada** [cryptlex/lexactivator-js#77]
Hey there,

when trying to use the `@cryptlex/lexactivator` package on Windows 11 with ARM64 processor, it fails with the following message:

```
PS C:\git\test-app> npx ts-node --project tsconfig.json hello-world.ts
Error: Cannot find module 'C:\git\test-app\node_modules\@cryptlex\lexactivator\lib\bindings\windows\arm64\lexactivator.node'
Require stack:
- C:\git\test-app\node_modules\@cryptlex\lexactivator\lib\lexactivator-native.js
- C:\git\test-app\node_modules\@cryptlex\lexactivator\lib\lexactivator.js
- C:\git\test-app\node_modules\@cryptlex\lexactivator\lib\index.js
- C:\git\test-app\hello-world.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\git\test-app\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\git\test-app\node_modules\@cryptlex\lexactivator\src\lexactivator-native.ts:10:35)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .js] (C:\git\test-app\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1037:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\git\\test-app\\node_modules\\@cryptlex\\lexactivator\\lib\\lexactivator-native.js',
    'C:\\git\\test-app\\node_modules\\@cryptlex\\lexactivator\\lib\\lexactivator.js',
    'C:\\git\\test-app\\node_modules\\@cryptlex\\lexactivator\\lib\\index.js',
    'C:\\git\\test-app\\hello-world.ts'
  ]
}
```
as bindings for arm64 aren't available for Windows, nor there are LexActivator library binaries present for arm64.

Could you please add these?

**Comment by ahmad-kemsan** [comment]
Hi @mhalada,

Thanks for reaching out.

Support for arm64 on Windows is already part of our roadmap, and it is expected to be available within the next two months. We will keep you informed as we make progress.

**Comment by ahmad-kemsan** [comment]
Hi @mhalada,

The support for windows arm64 has been added to LexActivator. Please upgrade the package version to the latest.
